# color-terminal — build, test, lint.
#
# The only build step that matters is `dist`: it concatenates lib/*.sh into ONE
# self-contained script. That is deliberate. A single file can be scp'd to any host
# you ssh into (which is how v1 worked and has to keep working), and it turns ten
# open() calls into one on a hot path that runs at every shell start.

SHELL := /bin/bash
# pipefail, so a failing tar in the dist recipe fails the build instead of quietly
# appending an empty payload — which is how a Mac would otherwise install zero themes.
.SHELLFLAGS := -o pipefail -c
PREFIX ?= $(HOME)/.local
DIST := dist/color-terminal

# GNU tar is required: the payload is normalised with --sort/--mtime/--owner/--mode,
# which bsdtar (macOS) does not have. Homebrew installs it as `gtar`.
TAR ?= $(shell command -v gtar 2>/dev/null || echo tar)

# One source list, read here and by bin/color-terminal, so the artifact and the
# checkout cannot disagree about what the tool is made of. Order is load-bearing.
LIBS := $(shell sed -e 's/\#.*//' -e '/^[[:space:]]*$$/d' lib/manifest)
PAYLOAD := $(wildcard themes/*.theme) $(wildcard shell/*.in)

.PHONY: all dist lint test test-live test-terminals golden themes docs install uninstall clean
# A recipe that fails must not leave its target behind: the dist recipe writes the
# code half first and the payload second, and a half-written artifact that make then
# considers up to date is exactly the hollow file this rule exists to prevent.
.DELETE_ON_ERROR:

all: dist

dist: $(DIST)

$(DIST): $(LIBS) $(PAYLOAD) lib/manifest Makefile
	@$(TAR) --version 2>/dev/null | grep -q 'GNU tar' \
	  || { echo "dist: needs GNU tar for a reproducible payload (found: $$($(TAR) --version 2>&1 | head -1)). On macOS: brew install gnu-tar" >&2; exit 1; }
	@mkdir -p dist
	@{ \
	  echo '#!/usr/bin/env bash'; \
	  echo '# color-terminal — generated by `make dist`. Do not edit; edit lib/*.sh.'; \
	  echo '# Single file on purpose: it has to survive being scp+'"'"'d to a bare remote host.'; \
	  echo 'set -uo pipefail'; \
	  echo 'CT_REPO_DIR='; \
	  for f in $(LIBS); do echo; echo "# ---- $$f ----"; sed -e '1{/^#!/d}' "$$f"; done; \
	  echo; echo 'ct_main "$$@"'; \
	  echo 'exit $$?'; \
	} > $(DIST)
	@# Everything the tool needs at runtime rides inside this one file. It is appended
	@# AFTER the final `exit`, so bash never parses it and it costs nothing at shell
	@# start; --install reads the file's own tail to get it back. This is what keeps
	@# `scp color-terminal remote:` a working install, and what lets the release be one
	@# raw file that installs with download -> verify -> chmod and nothing else.
	@echo '#__CT_PAYLOAD__' >> $(DIST)
	@# Normalised so the artifact is REPRODUCIBLE: plain `tar czf` records each file's
	@# mtime, the builder's uid/gid AND each file's mode, and git rewrites mtimes on
	@# every fresh clone while umask decides the mode — so CI and a laptop would build
	@# different bytes from identical source. Publishing a sha256 only means something
	@# if anyone can rebuild the file and get the same one.
	@#   --mode: a-x first strips whatever the checkout had, then u=rwX,go=rX gives
	@#   files 644 and directories 755 whatever the umask was. X is x-if-directory.
	@$(TAR) --sort=name --mtime=@0 --owner=0 --group=0 --numeric-owner \
	    --mode='a-x,u=rwX,go=rX' -cf - themes shell \
	  | gzip -n | base64 >> $(DIST)
	@chmod +x $(DIST)
	@bash -n $(DIST) && echo "dist: $(DIST) ($$(wc -l < $(DIST)) lines, $$(wc -c < $(DIST)) bytes)"

lint:
	@fail=0; \
	for f in lib/*.sh lib/backends/*.sh lib/sinks/*.sh; do \
	  case " $(LIBS) " in *" $$f "*) ;; *) echo "lint: $$f exists but is not listed in lib/manifest"; fail=1 ;; esac; \
	done; \
	for f in bin/color-terminal install.sh test/ci-gate.sh $(LIBS); do bash -n "$$f" || fail=1; done; \
	bash -n shell/color-terminal.bash.in || fail=1; \
	command -v zsh >/dev/null && { zsh -n shell/color-terminal.zsh.in || fail=1; }; \
	sh -n docs/install.sh test/ci-gate.sh || fail=1; \
	command -v dash >/dev/null && { dash -n docs/install.sh && dash -n test/ci-gate.sh || fail=1; }; \
	if command -v shellcheck >/dev/null; then \
	  shellcheck -x -S warning bin/color-terminal install.sh $(LIBS) || fail=1; \
	  shellcheck -s sh -S warning docs/install.sh test/ci-gate.sh || fail=1; \
	else echo "lint: shellcheck NOT INSTALLED (pacman -S shellcheck). This is the weak"; \
	     echo "lint: gate — CI runs the strong one and WILL fail on what this misses."; fi; \
	python3 -m py_compile tools/*.py || fail=1; \
	python3 tools/validate-themes.py || fail=1; \
	python3 tools/check-site.py docs/index.html || fail=1; \
	exit $$fail

test: dist
	@test/run.sh

test-live:
	@test/live/run.sh

test-terminals:
	@test/containers/run.sh

golden:
	@test/gen-golden.sh

themes:
	@tools/import-scheme.sh --all

# The generated sections of the website, rebuilt from themes/ and the backend
# registry. CI runs this and fails if the page changes, so the swatches and the
# terminal tiers on the web are always what the tool actually ships.
docs:
	@python3 tools/gen-site.py
	@python3 tools/check-site.py docs/index.html

install: dist
	@./install.sh

uninstall:
	@./install.sh --uninstall

clean:
	@rm -rf dist
