# color-terminal — build, test, lint.
#
# The only build step that matters is `dist`: it concatenates lib/*.sh into ONE
# self-contained script. That is deliberate. A single file can be scp'd to any host
# you ssh into (which is how v1 worked and has to keep working), and it turns ten
# open() calls into one on a hot path that runs at every shell start.

SHELL := /bin/bash
PREFIX ?= $(HOME)/.local
DIST := dist/color-terminal

# Order is load-bearing: definitions before use, backends before main dispatches to
# them, and it must match the source order in bin/color-terminal.
LIBS := lib/common.sh lib/config.sh lib/theme.sh lib/pick.sh lib/state.sh \
        lib/detect.sh lib/emit.sh lib/rcsplice.sh lib/backend.sh \
        lib/backends/generic.sh lib/backends/ghostty.sh lib/backends/foot.sh \
        lib/sinks/splashboard.sh lib/doctor.sh lib/main.sh

.PHONY: all dist lint test test-live test-terminals golden themes docs install uninstall clean

all: dist

dist: $(DIST)

$(DIST): $(LIBS)
	@mkdir -p dist
	@{ \
	  echo '#!/usr/bin/env bash'; \
	  echo '# color-terminal — generated by `make dist`. Do not edit; edit lib/*.sh.'; \
	  echo '# Single file on purpose: it has to survive being scp+'"'"'d to a bare remote host.'; \
	  echo 'set -uo pipefail'; \
	  echo 'CT_REPO_DIR='; \
	  for f in $(LIBS); do echo; echo "# ---- $$f ----"; sed -e '1{/^#!/d}' "$$f"; done; \
	  echo; echo 'ct_main "$$@"'; \
	} > $(DIST)
	@chmod +x $(DIST)
	@bash -n $(DIST) && echo "dist: $(DIST) ($$(wc -l < $(DIST)) lines)"

lint:
	@fail=0; \
	for f in bin/color-terminal install.sh $(LIBS); do bash -n "$$f" || fail=1; done; \
	bash -n shell/color-terminal.bash.in || fail=1; \
	command -v zsh >/dev/null && { zsh -n shell/color-terminal.zsh.in || fail=1; }; \
	if command -v shellcheck >/dev/null; then \
	  shellcheck -x -S warning bin/color-terminal install.sh $(LIBS) || fail=1; \
	else echo "lint: shellcheck not installed (pacman -S shellcheck) — syntax only"; fi; \
	python3 tools/validate-themes.py || fail=1; \
	exit $$fail

test: dist
	@test/run.sh

test-live:
	@test/live/run.sh

test-terminals:
	@test/containers/run.sh

golden:
	@test/gen-golden.sh

themes:
	@tools/import-scheme.sh --all

install: dist
	@./install.sh

uninstall:
	@./install.sh --uninstall

clean:
	@rm -rf dist
