# color-terminal — build, test, lint.
#
# The only build step that matters is `dist`: it concatenates lib/*.sh into ONE
# self-contained script. That is deliberate. A single file can be scp'd to any host
# you ssh into (which is how v1 worked and has to keep working), and it turns ten
# open() calls into one on a hot path that runs at every shell start.

SHELL := /bin/bash
PREFIX ?= $(HOME)/.local
DIST := dist/color-terminal

# Order is load-bearing: definitions before use, backends before main dispatches to
# them, and it must match the source order in bin/color-terminal.
LIBS := lib/common.sh lib/config.sh lib/theme.sh lib/pick.sh lib/state.sh \
        lib/detect.sh lib/emit.sh lib/rcsplice.sh lib/backend.sh \
        lib/backends/generic.sh lib/backends/ghostty.sh lib/backends/foot.sh \
        lib/sinks/splashboard.sh lib/doctor.sh lib/install.sh lib/main.sh

.PHONY: all dist lint test test-live test-terminals golden themes docs install uninstall clean

all: dist

dist: $(DIST)

$(DIST): $(LIBS)
	@mkdir -p dist
	@{ \
	  echo '#!/usr/bin/env bash'; \
	  echo '# color-terminal — generated by `make dist`. Do not edit; edit lib/*.sh.'; \
	  echo '# Single file on purpose: it has to survive being scp+'"'"'d to a bare remote host.'; \
	  echo 'set -uo pipefail'; \
	  echo 'CT_REPO_DIR='; \
	  for f in $(LIBS); do echo; echo "# ---- $$f ----"; sed -e '1{/^#!/d}' "$$f"; done; \
	  echo; echo 'ct_main "$$@"'; \
	  echo 'exit $$?'; \
	} > $(DIST)
	@# Everything the tool needs at runtime rides inside this one file. It is appended
	@# AFTER the final `exit`, so bash never parses it and it costs nothing at shell
	@# start; --install reads the file's own tail to get it back. This is what keeps
	@# `scp color-terminal remote:` a working install, and what lets the release be one
	@# raw file that installs with download -> verify -> chmod and nothing else.
	@echo '#__CT_PAYLOAD__' >> $(DIST)
	@# Normalised so the artifact is REPRODUCIBLE: plain `tar czf` records each file's
	@# mtime and the builder's uid/gid, and git rewrites mtimes on every fresh clone, so
	@# CI and a laptop would produce different bytes for identical source. Publishing a
	@# sha256 only means something if anyone can rebuild the file and get the same one.
	@tar --sort=name --mtime=@0 --owner=0 --group=0 --numeric-owner -cf - themes shell \
	  | gzip -n | base64 >> $(DIST)
	@chmod +x $(DIST)
	@bash -n $(DIST) && echo "dist: $(DIST) ($$(wc -l < $(DIST)) lines, $$(wc -c < $(DIST)) bytes)"

lint:
	@fail=0; \
	for f in bin/color-terminal install.sh $(LIBS); do bash -n "$$f" || fail=1; done; \
	bash -n shell/color-terminal.bash.in || fail=1; \
	command -v zsh >/dev/null && { zsh -n shell/color-terminal.zsh.in || fail=1; }; \
	sh -n docs/install.sh || fail=1; \
	command -v dash >/dev/null && { dash -n docs/install.sh || fail=1; }; \
	if command -v shellcheck >/dev/null; then \
	  shellcheck -x -S warning bin/color-terminal install.sh $(LIBS) || fail=1; \
	  shellcheck -s sh -S warning docs/install.sh || fail=1; \
	else echo "lint: shellcheck NOT INSTALLED (pacman -S shellcheck). This is the weak"; \
	     echo "lint: gate — CI runs the strong one and WILL fail on what this misses."; fi; \
	python3 tools/validate-themes.py || fail=1; \
	exit $$fail

test: dist
	@test/run.sh

test-live:
	@test/live/run.sh

test-terminals:
	@test/containers/run.sh

golden:
	@test/gen-golden.sh

themes:
	@tools/import-scheme.sh --all

# The three generated sections of the website, rebuilt from themes/*.theme. CI runs
# this and fails if the page changes, so the swatches on the web are always the colours
# the tool actually ships.
docs:
	@python3 tools/gen-site.py

install: dist
	@./install.sh

uninstall:
	@./install.sh --uninstall

clean:
	@rm -rf dist
