# shellcheck shell=bash
# SC2034: globals are written in one fragment and read in another.
# shellcheck disable=SC2034
# foot — tier 1. Installed on the author's machine, so it is the second terminal that
# gets dogfooded rather than mocked.
#
# foot has the best escape coverage of anything in the corpus: OSC 4/10/11/12 AND
# 17/19 for selection, with the full 104/110/111/112/117/119 reset set (man 7
# foot-ctlseqs). It is therefore the terminal that proves the selection-colour path is
# not dead code — and the one that would have caught v1's missing 117/119 resets.
#
# Everything below was read out of `man 5 foot.ini` on foot 1.27, not inferred:
#  * colours are bare RRGGBB with NO leading '#'
#  * the sections are [colors-dark] and [colors-light]; plain [colors] is gone
#  * `cursor` takes TWO values, "<text> <cursor>" — the text colour first. Getting
#    this backwards is invisible until you look at a cursor sitting on a character.
#  * `include` requires an ABSOLUTE path; it does not expand ~

ct_be_foot_detect() {
    if [ "${TERM_PROGRAM:-}" = foot ] && ct_env_local; then
        CT_CONF=certain; CT_LOCAL=1; return 0
    fi
    if ct_term_is 'foot*'; then
        CT_CONF=probable; return 0
    fi
    return 1
}

ct_be_foot_caps() {
    printf 'set4 set10 set11 set12 set17 set19 rst104 rst110 rst111 rst112 rst117 rst119 persist'
}

ct_be_foot_fragment() {
    printf '%s/foot/color-terminal.ini\n' "${XDG_CONFIG_HOME:-$HOME/.config}"
}

# Strip the '#' foot does not want. One parameter expansion per value, no fork.
ct_be_foot_render() {
    local i
    printf '# Generated by color-terminal — rewritten on every swap. Do not edit.\n'
    printf '# Theme: %s (%s)\n' "$CT_NAME" "$CT_THEME_ID"
    # Written into BOTH sections on purpose. foot picks one of them at startup
    # (initial-color-theme) and lets the user toggle at runtime; since we are supplying
    # the whole palette anyway, filling both means the theme is what you asked for
    # regardless of which mode the window happens to be in.
    local section
    for section in colors-dark colors-light; do
        printf '\n[%s]\n' "$section"
        printf 'foreground=%s\n' "${CT_FG#\#}"
        printf 'background=%s\n' "${CT_BG#\#}"
        for ((i = 0; i < 8; i++)); do
            printf 'regular%d=%s\n' "$i" "${CT_PAL[i]#\#}"
        done
        for ((i = 8; i < 16; i++)); do
            printf 'bright%d=%s\n' "$((i - 8))" "${CT_PAL[i]#\#}"
        done
        # text colour first, cursor block second
        printf 'cursor=%s %s\n' "${CT_CURSOR_TEXT#\#}" "${CT_CURSOR#\#}"
        printf 'selection-foreground=%s\n' "${CT_SEL_FG#\#}"
        printf 'selection-background=%s\n' "${CT_SEL_BG#\#}"
    done
}

ct_be_foot_persist() { ct_move_atomic "$1" "$(ct_be_foot_fragment)"; }

ct_be_foot_wire() {
    local cfg="${XDG_CONFIG_HOME:-$HOME/.config}/foot/foot.ini"
    local frag; frag=$(ct_be_foot_fragment)
    ct_has_block "$cfg" "$CT_MARK_BEGIN" && return 3

    # foot treats a missing include as a hard startup error, so the fragment has to
    # exist before the include line does. A placeholder is enough; the first swap
    # overwrites it.
    if [ ! -e "$frag" ]; then
        ct_mkdir "${frag%/*}"
        printf '# Placeholder written by color-terminal at install time.\n' > "$frag"
    fi

    # foot's config search is FIRST MATCH, not a merge: the moment ~/.config/foot/foot.ini
    # exists, /etc/xdg/foot/foot.ini stops being read entirely. On a machine where the
    # distro ships defaults there (CachyOS does not, but Fedora and others do),
    # creating our file would silently throw those away. So seed the new file with an
    # include of the system one first.
    if [ ! -e "$cfg" ]; then
        ct_mkdir "${cfg%/*}"
        if [ -r /etc/xdg/foot/foot.ini ]; then
            {
                printf '# Created by color-terminal. foot reads only the FIRST config it finds,\n'
                printf '# so this line keeps your distribution defaults in play.\n'
                printf 'include=/etc/xdg/foot/foot.ini\n'
            } > "$cfg"
        else
            : > "$cfg"
        fi
    fi

    ct_splice_block "$cfg" "$CT_MARK_BEGIN" "$CT_MARK_END" <<EOF
# Loads the palette color-terminal writes. foot requires an absolute path here.
include=$frag
EOF
}

ct_be_foot_unwire() {
    local cfg="${XDG_CONFIG_HOME:-$HOME/.config}/foot/foot.ini"
    # Order matters and is the inverse of wire: drop the include line first, because a
    # foot.ini pointing at a file we already deleted refuses to start.
    ct_unsplice_block "$cfg" "$CT_MARK_BEGIN" "$CT_MARK_END"
    rm -f "$(ct_be_foot_fragment)"
    return 0
}
