# shellcheck shell=bash
# SC2034: globals are written in one fragment and read in another.
# shellcheck disable=SC2034
# tier: 1
# name: ghostty
# ghostty — tier 1. The incumbent backend and the author's daily driver.
#
# Capability notes, verified against ghostty 1.3.1:
#  * OSC 4/10/11/12 are implemented. 17/19 (selection) are NOT: ghostty logs
#    "setting dynamic color not implemented" for them, so sending them is noise.
#  * OSC-set colours OUTRANK the config file and survive a config reload
#    (src/terminal/color.zig: changeDefault preserves mask-set entries, and
#    DynamicRGB.get returns `override orelse default`). That is fine here because we
#    only ever write the fragment for the theme we are also emitting — the two can
#    never disagree — but it is why "reset then reload" would be needed if they could.

ct_be_ghostty_detect() {
    # GHOSTTY_RESOURCES_DIR is exported by the ghostty process itself and is not
    # forwarded over ssh, so it is precisely the question "am I inside the terminal I
    # am about to recolour?".
    if [ -n "${GHOSTTY_RESOURCES_DIR:-}" ] && ct_env_local; then
        CT_CONF=certain; CT_LOCAL=1; return 0
    fi
    if [ "${TERM_PROGRAM:-}" = ghostty ] && ct_env_local; then
        CT_CONF=certain; CT_LOCAL=1; return 0
    fi
    if ct_term_is 'xterm-ghostty*'; then
        CT_CONF=probable; return 0            # travels over ssh; says nothing about locality
    fi
    return 1
}

ct_be_ghostty_caps() {
    printf 'set4 set10 set11 set12 rst104 rst110 rst111 rst112 persist'
}

ct_be_ghostty_fragment() {
    printf '%s/ghostty/color-terminal.conf\n' "${XDG_CONFIG_HOME:-$HOME/.config}"
}

ct_be_ghostty_render() {
    local i
    printf '# Generated by color-terminal — rewritten on every swap. Do not edit.\n'
    printf '# Theme: %s (%s)\n\n' "$CT_NAME" "$CT_THEME_ID"
    for ((i = 0; i < 16; i++)); do
        printf 'palette = %d=%s\n' "$i" "${CT_PAL[i]}"
    done
    printf 'background = %s\n' "$CT_BG"
    printf 'foreground = %s\n' "$CT_FG"
    printf 'cursor-color = %s\n' "$CT_CURSOR"
    printf 'cursor-text = %s\n' "$CT_CURSOR_TEXT"
    printf 'selection-background = %s\n' "$CT_SEL_BG"
    printf 'selection-foreground = %s\n' "$CT_SEL_FG"
}

ct_be_ghostty_persist() { ct_move_atomic "$1" "$(ct_be_ghostty_fragment)"; }

ct_be_ghostty_wire() {
    local cfg="${XDG_CONFIG_HOME:-$HOME/.config}/ghostty/config"
    ct_has_block "$cfg" "$CT_MARK_BEGIN" && return 3
    # The `?` prefix means "ignore this include if the file is missing", so a
    # half-finished install can never stop ghostty from starting.
    #
    # An included file is loaded AFTER the file that includes it and its values win,
    # so this overrides an existing `theme =` line without touching it. That matters:
    # the user's line may be the light/dark form `theme = light:X,dark:Y`, which v1's
    # sed destroyed.
    ct_splice_block "$cfg" "$CT_MARK_BEGIN" "$CT_MARK_END" <<'EOF'
# Loads the palette color-terminal writes. Included files win over the lines above,
# so your own `theme =` is left exactly as you wrote it. Delete this block to stop.
config-file = ?color-terminal.conf
EOF
}

ct_be_ghostty_unwire() {
    local cfg="${XDG_CONFIG_HOME:-$HOME/.config}/ghostty/config"
    ct_unsplice_block "$cfg" "$CT_MARK_BEGIN" "$CT_MARK_END"
    rm -f "$(ct_be_ghostty_fragment)"
    return 0
}
